#include "web_ui.h"

#ifndef OPENWATTS_FIRMWARE_VERSION
#define OPENWATTS_FIRMWARE_VERSION "development"
#endif

namespace openwatts::webui {

#define PAGE_HEAD(TITLE, STATUS, SETTINGS, CALIBRATION, OTA, DIAGNOSTICS) \
    "<!doctype html><html lang=en><head><meta charset=utf-8><meta name=viewport content='width=device-width,initial-scale=1'>" \
    "<title>" TITLE " · OpenWatts</title><style>" \
    ":root{color-scheme:dark;--bg:#101010;--surface:#1a1a1a;--raised:#242424;--line:#383838;--text:#f2f2f2;--muted:#aaa;--good:#68d391;--warn:#e6c66a;--bad:#ff7878;--radius:12px;--space:14px}" \
    "*{box-sizing:border-box}html{background:var(--bg)}body{margin:0;color:var(--text);background:var(--bg);font:15px system-ui,-apple-system,Segoe UI,sans-serif;line-height:1.4}" \
    "header{position:sticky;top:0;z-index:5;background:#151515f2;border-bottom:1px solid var(--line);backdrop-filter:blur(10px)}" \
    ".bar{max-width:1100px;min-width:0;margin:auto;padding:12px 14px;display:grid;grid-template-columns:minmax(0,1fr) auto;align-items:center;gap:8px 12px}.brandwrap{display:flex;align-items:center;gap:10px;min-width:0}.logo{width:30px;height:30px;border:1px solid #555;border-radius:8px;display:grid;place-items:center;color:#777;font-size:11px}.brand{font-size:20px;font-weight:800;white-space:nowrap}.uptime{color:var(--muted);font-size:12px;font-style:italic;text-align:right}" \
    "nav{grid-column:1/-1;display:flex;gap:4px;min-width:0;max-width:100%;overflow-x:auto;scrollbar-width:thin}nav a{color:var(--muted);text-decoration:none;padding:10px 11px;border-radius:8px;white-space:nowrap;min-height:42px;display:flex;align-items:center}nav a:hover,nav a.active{background:#303030;color:var(--text)}" \
    "main{width:100%;max-width:1100px;min-width:0;margin:auto;padding:20px 14px 52px;overflow-x:hidden}.title{display:flex;justify-content:space-between;align-items:end;gap:12px;margin-bottom:17px;min-width:0}.title h1{font-size:27px;line-height:1.15;margin:0}.title small,.sub,.helptext{color:var(--muted)}" \
    ".grid{display:grid;grid-template-columns:minmax(0,1fr);gap:12px;min-width:0}.card{min-width:0;background:var(--surface);border:1px solid var(--line);border-radius:var(--radius);padding:16px}.card h2{font-size:17px;margin:0 0 13px}.hero{font-size:40px;font-weight:800;line-height:1.05}.metric{font-size:24px;font-weight:750}.eyebrow{color:var(--muted);font-size:12px;text-transform:uppercase;letter-spacing:.06em}.badge{display:inline-flex;align-items:center;gap:6px;border:1px solid #555;border-radius:999px;padding:5px 9px;background:#222;font-size:13px}.badge.good{border-color:#397452;color:var(--good)}.badge.warn{border-color:#78652c;color:var(--warn)}.badge.bad{border-color:#7d3e45;color:var(--bad)}" \
    "dl{display:grid;grid-template-columns:minmax(125px,1fr) auto;gap:9px 14px;margin:0}dt{color:var(--muted)}dd{margin:0;text-align:right;font-weight:650;overflow-wrap:anywhere}.section{margin-top:18px}.sectiontitle{display:flex;align-items:center;gap:8px;margin:0 0 10px}.sectiontitle h2{font-size:19px;margin:0}" \
    "label{display:block;color:var(--muted);margin:12px 0 5px}.field{position:relative}input,select{width:100%;border:1px solid #505050;background:#121212;color:var(--text);border-radius:9px;padding:12px;font:inherit;min-height:46px}.check{display:flex;align-items:center;gap:10px;color:var(--text);margin:13px 0;min-height:44px}.check input{width:20px;height:20px;min-height:auto}.info{display:inline-grid;place-items:center;width:22px;height:22px;border:1px solid #555;border-radius:50%;color:var(--muted);font-size:12px;cursor:help;position:relative}.info:hover:after,.info:focus:after{content:attr(data-help);position:absolute;z-index:9;left:0;top:28px;width:min(270px,75vw);padding:9px;border:1px solid #555;border-radius:8px;background:#292929;color:var(--text);font-weight:400;box-shadow:0 8px 30px #0008}" \
    "button,.button{appearance:none;border:1px solid #555;background:#303030;color:var(--text);border-radius:9px;padding:12px 15px;min-height:46px;font:inherit;font-weight:700;cursor:pointer;text-decoration:none}button:hover,.button:hover{background:#3a3a3a;border-color:#888}button:disabled{opacity:.45;cursor:not-allowed}.actions{display:flex;flex-wrap:wrap;gap:10px}.result{min-height:48px;margin-top:12px;padding:12px;border:1px solid var(--line);border-radius:9px;background:#121212;white-space:pre-wrap}.result.ok{border-color:#397452;color:var(--good)}.result.bad{border-color:#7d3e45;color:var(--bad)}.result.pending{border-color:#78652c;color:var(--warn)}progress{width:100%;height:16px;margin:12px 0}" \
    ".placeholder{border-style:dashed}.steps{display:grid;gap:9px;counter-reset:step}.step{display:grid;grid-template-columns:28px 1fr;gap:10px;align-items:start}.step:before{counter-increment:step;content:counter(step);display:grid;place-items:center;width:26px;height:26px;border-radius:50%;background:var(--raised);color:var(--muted);font-weight:700}.mono{font-family:ui-monospace,SFMono-Regular,Consolas,monospace}.footer-note{margin-top:18px;color:var(--muted);font-size:13px}" \
    "@media(max-width:699px){.title{align-items:flex-start;flex-direction:column}.title small{overflow-wrap:anywhere}dl{grid-template-columns:minmax(0,1fr) minmax(0,auto)}dd{max-width:52vw}.hero{font-size:36px}}@media(min-width:700px){.bar{display:flex;padding:13px 18px}.brandwrap{margin-right:6px}nav{grid-column:auto;flex:1}.uptime{order:3}.grid.two{grid-template-columns:repeat(2,minmax(0,1fr))}.grid.three{grid-template-columns:repeat(3,minmax(0,1fr))}main{padding:24px 18px 54px}.title h1{font-size:30px}}" \
    "</style></head><body><header><div class=bar><div class=brandwrap><div class=logo aria-label='Logo placeholder'>OW</div><div class=brand>OpenWatts</div></div><nav aria-label='Primary'>" \
    "<a " STATUS " href=/>Status</a><a " SETTINGS " href=/settings>Settings</a><a " CALIBRATION " href=/calibration>Calibration</a><a " OTA " href=/ota>OTA Update</a><a " DIAGNOSTICS " href=/diagnostics>Diagnostics</a>" \
    "</nav><span class=uptime id=navUptime>Uptime: --</span></div></header><main><div class=title><h1>" TITLE "</h1><small>Firmware " OPENWATTS_FIRMWARE_VERSION "</small></div>"

#define PAGE_FOOT "</main></body></html>"

#define CORE_JS \
    "const $=id=>document.getElementById(id),put=(id,v)=>{const e=$(id);if(e)e.textContent=v},fmt=(v,n=2)=>Number.isFinite(Number(v))?Number(v).toFixed(n):'--';" \
    "async function getStatus(){const r=await fetch('/status',{cache:'no-store'});if(!r.ok)throw Error('HTTP '+r.status);return r.json()}" \
    "function uptime(v){v=Math.max(0,Math.floor(Number(v)||0));const d=Math.floor(v/86400);v%=86400;const h=Math.floor(v/3600);v%=3600;return`Uptime: ${d}d ${h}h ${Math.floor(v/60)}m ${v%60}s`}" \
    "let up=0;async function syncUp(){try{const s=await getStatus();up=s.uptime||0;put('navUptime',uptime(up))}catch(e){}}syncUp();setInterval(()=>{up++;put('navUptime',uptime(up))},1000);setInterval(syncUp,30000);"

const char kStatusPage[] = PAGE_HEAD("Device Status", "class=active", "", "", "", "")
    "<div class='grid two'><section class=card><div class=eyebrow>Live output</div><h2>Power</h2><div class=hero><span id=power>--</span> <small>W</small></div><div class=sub><span id=cadence>--</span> RPM · <span id=torque>--</span></div></section>"
    "<section class=card><div class=eyebrow>Energy</div><h2>Battery</h2><div class=hero id=battery>--</div><div class=sub><span id=voltage>--</span> · <span id=charge>--</span></div></section>"
    "<section class=card><h2>Connections</h2><dl><dt>Bluetooth</dt><dd id=ble>--</dd><dt>Wi-Fi</dt><dd id=wifi>--</dd><dt>USB</dt><dd id=usb>--</dd></dl></section>"
    "<section class=card><h2>Readiness</h2><dl><dt>Device health</dt><dd><span class='badge good' id=health>Checking</span></dd><dt>IMU</dt><dd id=imu>--</dd><dt>Strain sensor</dt><dd id=hx>--</dd><dt>Calibration</dt><dd id=cal>--</dd></dl></section></div>"
    "<section class='card section placeholder'><div class=sectiontitle><h2>Last Ride</h2><span class=badge>Planned</span></div><p class=sub>Ride summaries will appear here after ride-history storage is introduced.</p></section><div class=result id=live>Connecting to OpenWatts…</div>"
    "<script>" CORE_JS "async function refresh(){try{const s=await getStatus();put('power',s.calibrated?s.power:'--');put('cadence',fmt(s.cadence,1));put('torque',s.calibrated?fmt(s.torque,2)+' Nm':'Not calibrated');put('battery',s.battery_valid?s.battery_percent+'%':'Unavailable');put('voltage',s.battery_valid?fmt(s.battery_voltage,2)+' V':'No valid reading');put('charge',s.charging?'Charging':'Not charging');put('ble',s.ble?'Connected':'Advertising');put('wifi','Active'+(s.wifi_battery?' · battery override':''));put('usb',s.usb?'Connected':'Disconnected');put('imu',s.imu?'Ready':'Unavailable');put('hx',s.hx?'Detected':'Unavailable');put('cal',s.calibrated?'Valid':'Required');put('health',s.imu&&s.hx?'Healthy':'Attention needed');$('health').className='badge '+(s.imu&&s.hx?'good':'warn');$('live').className='result ok';put('live','Live update · '+new Date().toLocaleTimeString())}catch(e){$('live').className='result bad';put('live','Device is not responding · '+e.message)}setTimeout(refresh,1000)}refresh()</script>" PAGE_FOOT;

const char kSettingsPage[] = PAGE_HEAD("Settings", "", "class=active", "", "", "")
    "<form id=settings><div class='grid two'><section class=card><div class=sectiontitle><h2>Network</h2><span class=info tabindex=0 data-help='Wi-Fi is normally available while USB is connected. The override keeps it active on battery for setup and testing.'>i</span></div><label>Wi-Fi network</label><input name=ssid id=ssid maxlength=32 autocomplete=off><label>Password</label><input name=password type=password maxlength=64 autocomplete=new-password placeholder='Leave blank to keep current password'><label class=check><input type=checkbox name=wifi_battery id=wifiBattery> Keep Wi-Fi on without USB</label><p class=sub>Battery override applies immediately and increases power use.</p></section>"
    "<section class=card><div class=sectiontitle><h2>Notifications</h2><span class=info tabindex=0 data-help='Publishes battery information to the configured MQTT broker when the reporting policy requires it.'>i</span></div><label class=check><input type=checkbox name=mqtt_enabled id=mqttEnabled> Enable MQTT battery reporting</label><label>Broker address</label><input name=mqtt_host id=mqttHost maxlength=63><div class='grid two'><div><label>Port</label><input name=mqtt_port id=mqttPort type=number min=1 max=65535></div><div><label>Topic</label><input name=mqtt_topic id=mqttTopic maxlength=95></div></div></section>"
    "<section class=card><div class=sectiontitle><h2>Power & Sleep</h2><span class=info tabindex=0 data-help='Motion-wake sleep stops radios and sampling after the idle delay. Motion or USB wakes the device.'>i</span></div><label class=check><input type=checkbox name=sleep id=sleep> Enable motion-wake sleep</label><label>Idle delay before sleep</label><div class='grid two'><input id=timeoutValue type=number min=5 max=3600 step=1><select id=timeoutUnit aria-label='Idle delay unit'><option value=1>seconds</option><option value=60>minutes</option></select></div><input name=timeout id=timeoutRaw type=hidden><label>Power smoothing</label><input name=power_filter_alpha id=powerAlpha type=number min=.05 max=1 step=.05><p class=sub>0.05 is smoother; 1.00 reacts fastest. Applies after restart.</p><label>Maximum believable power</label><div class='grid two'><input name=maximum_valid_power_watts id=maxPower type=number min=500 max=5000 step=50><input value=watts disabled aria-label='Power unit'></div><p class=sub>Samples above this limit are rejected. Applies after restart.</p></section>"
    "<section class=card><div class=sectiontitle><h2>Bluetooth</h2><span class=info tabindex=0 data-help='The saved name is used for Bluetooth advertising and the GATT device name after restart.'>i</span></div><label>Device name</label><input name=ble_name id=bleName maxlength=18 pattern='[A-Za-z0-9 _-]+'><p class=sub>Letters, numbers, spaces, hyphens, and underscores. Applies after restart.</p><label>Advertising power</label><select disabled><option>Default radio power</option></select><p class=sub>Available after firmware support.</p><label>Connection behavior</label><select disabled><option>Advertise automatically</option></select><p class=sub>Current behavior is fixed by the Cycling Power service.</p></section>"
    "<section class=card><div class=sectiontitle><h2>Ride Behavior</h2><span class=info tabindex=0 data-help='Ride controls will be enabled only after their sensing algorithms are validated on the installed crank.'>i</span></div><label class=check><input type=checkbox disabled> Automatic Ride Zero</label><p class=sub>Requires validated strain-bridge zeroing.</p><label class=check><input type=checkbox disabled> Automatic ride detection</label><p class=sub>Requires ride-lifecycle firmware support.</p><label>Minimum ride duration</label><input id=minRide disabled><p class=sub>Configuration is reserved; no runtime algorithm uses it yet.</p><label>Cadence timeout</label><input id=cadenceTimeout disabled><p class=sub>Requires validated IMU cadence detection.</p></section>"
    "<section class=card><div class=sectiontitle><h2>Motion Detection</h2><span class=info tabindex=0 data-help='These values remain read-only until installed-crank IMU validation is complete.'>i</span></div><label>Motion sensitivity</label><input id=motionSensitivity disabled><p class=sub>Current saved value; editing is unsafe before wake testing.</p><label>Rotation detection threshold</label><input id=rotationThreshold disabled><p class=sub>Requires installed-crank validation.</p><label class=check><input id=rotationAware type=checkbox disabled> Rotation-aware power</label><p class=sub>Requires validated crank-angle detection.</p></section>"
    "<section class=card><div class=sectiontitle><h2>Engineering</h2><span class=info tabindex=0 data-help='Ride diagnostics enables the existing riding telemetry log and can increase log volume.'>i</span></div><label class=check><input name=ride_diagnostics id=rideDiagnostics type=checkbox> Ride diagnostics</label><p class=sub>Applies immediately. Intended for sensor validation.</p><label class=check><input id=debugLogging type=checkbox disabled> Debug logging</label><p class=sub>Configuration is reserved; runtime log-level control is not implemented.</p></section>"
    "</div><div class='actions section'><button>Save Settings</button></div><div class=result id=saveResult>Loading settings from OpenWatts…</div></form>"
    "<script>" CORE_JS "async function load(){try{const s=await getStatus(),c=s.config||{};$('ssid').value=c.wifi_ssid||'';$('wifiBattery').checked=!!c.wifi_keep_alive_without_usb;$('mqttEnabled').checked=!!c.mqtt_enabled;$('mqttHost').value=c.mqtt_host||'';$('mqttPort').value=c.mqtt_port||1883;$('mqttTopic').value=c.mqtt_topic||'';$('sleep').checked=!!c.light_sleep_enabled;let sec=Math.max(5,Math.round((c.inactivity_timeout_ms||60000)/1000));if(sec>=120&&sec%60===0){$('timeoutValue').value=sec/60;$('timeoutUnit').value=60}else{$('timeoutValue').value=sec;$('timeoutUnit').value=1}$('bleName').value=c.ble_device_name||'OpenWatts';$('powerAlpha').value=Number(c.power_filter_alpha??.35).toFixed(2);$('maxPower').value=c.maximum_valid_power_watts||2000;$('rideDiagnostics').checked=!!c.ride_diagnostics_enabled;$('debugLogging').checked=!!c.debug_logging_enabled;$('minRide').value=(c.minimum_ride_duration_seconds||180)+' seconds';$('cadenceTimeout').value=(c.cadence_timeout_seconds||5)+' seconds';$('motionSensitivity').value=c.imu_wake_threshold??4;$('rotationThreshold').value=Number(c.imu_revolution_threshold_dps||120).toFixed(0)+' °/s';$('rotationAware').checked=!!c.rotation_aware_power_enabled;$('saveResult').className='result ok';put('saveResult','Settings loaded from OpenWatts.')}catch(e){$('saveResult').className='result bad';put('saveResult','Could not load settings · '+e.message)}}load();$('settings').onsubmit=async e=>{e.preventDefault();const out=$('saveResult');out.className='result pending';put('saveResult','Saving settings…');$('timeoutRaw').value=Math.round(Number($('timeoutValue').value)*Number($('timeoutUnit').value)*1000);try{const r=await fetch('/save',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams(new FormData(e.target))});const text=await r.text();let d={message:text};try{d=JSON.parse(text)}catch(_){}if(!r.ok)throw Error(d.message||'Save failed');await load();out.className='result ok';put('saveResult','✓ Settings saved and verified. Restart to apply Bluetooth, smoothing, power limit, or sleep-policy changes.')}catch(x){out.className='result bad';put('saveResult','Settings were not saved · '+x.message)}}</script>" PAGE_FOOT;

const char kCalibrationPage[] = PAGE_HEAD("Calibration", "", "", "class=active", "", "")
    "<div class='grid two'><section class=card><div class=sectiontitle><h2>Sensor Status</h2><span class=badge id=ready>Checking</span></div><dl><dt>HX711</dt><dd id=hx>--</dd><dt>Raw counts</dt><dd id=raw>--</dd><dt>Filtered counts</dt><dd id=filtered>--</dd><dt>Current offset</dt><dd id=zero>--</dd><dt>Calculated torque</dt><dd id=torque>--</dd></dl></section>"
    "<section class='card placeholder'><h2>Bench Calibration</h2><div class=steps><div class=step><div><strong>Prepare the crank</strong><div class=sub>Secure the crank and remove all load.</div></div></div><div class=step><div><strong>Capture references</strong><div class=sub>Record unloaded and known-load readings.</div></div></div><div class=step><div><strong>Verify and save</strong><div class=sub>Confirm direction and scale before use.</div></div></div></div><p class=footer-note>Calibration workflow will become available after strain bridge setup.</p><button disabled>Begin Bench Calibration</button></section>"
    "<section class='card placeholder'><h2>Ride Zero</h2><p class=sub>Runtime zeroing will be presented separately from permanent Bench Calibration.</p><button disabled>Establish Ride Zero</button></section><section class='card placeholder'><h2>Calibration History</h2><p class=sub>The latest calibration and verification record will appear here when history storage is available.</p></section></div>"
    "<script>" CORE_JS "async function refresh(){try{const s=await getStatus();put('hx',s.hx?'Detected':'Unavailable');put('raw',s.raw);put('filtered',fmt(s.filtered,2));put('zero',(s.config&&s.config.zero_offset)||0);put('torque',s.calibrated?fmt(s.torque,3)+' Nm':'Unavailable until calibrated');put('ready',s.hx?'Sensor ready':'Sensor unavailable');$('ready').className='badge '+(s.hx?'good':'warn')}catch(e){}setTimeout(refresh,1000)}refresh()</script>" PAGE_FOOT;

const char kOtaPage[] = PAGE_HEAD("OTA Update", "", "", "", "class=active", "")
    "<section class=card><div class=sectiontitle><h2>Install Firmware</h2><span class=badge id=usbBadge>Checking USB</span></div><p class=sub>Select PlatformIO's <span class=mono>firmware.bin</span>. Updates are accepted only while USB is connected.</p><label>Firmware binary</label><input id=file type=file accept=.bin,application/octet-stream><progress id=progress value=0 max=100></progress><div class=actions><button id=upload>Upload and Install</button></div><div class=result id=otaResult>Select a firmware binary.</div></section>"
    "<script>" CORE_JS "getStatus().then(s=>{put('usbBadge',s.usb?'USB connected':'USB required');$('usbBadge').className='badge '+(s.usb?'good':'warn');$('upload').disabled=!s.usb}).catch(()=>{});$('upload').onclick=()=>{const f=$('file').files[0],out=$('otaResult');if(!f||!f.name.toLowerCase().endsWith('.bin')){out.className='result bad';put('otaResult','Choose a valid .bin firmware image.');return}if(!confirm('Install '+f.name+' and reboot OpenWatts?'))return;const x=new XMLHttpRequest();x.open('POST','/ota/upload');x.setRequestHeader('Content-Type','application/octet-stream');out.className='result pending';$('upload').disabled=true;x.upload.onprogress=e=>{if(e.lengthComputable){const n=Math.round(e.loaded/e.total*100);$('progress').value=n;put('otaResult','Uploading · '+n+'%')}};x.onload=()=>{if(x.status<300){out.className='result ok';put('otaResult','Update installed. OpenWatts is rebooting; this page will reconnect automatically.');setTimeout(()=>location.href='/',5000)}else{out.className='result bad';put('otaResult',x.responseText||'Update failed');$('upload').disabled=false}};x.onerror=()=>{out.className='result bad';put('otaResult','Upload connection failed.');$('upload').disabled=false};x.send(f)}</script>" PAGE_FOOT;

const char kDiagnosticsPage[] = PAGE_HEAD("Diagnostics", "", "", "", "", "class=active")
    "<div class='grid two'><section class=card><h2>Battery & USB</h2><dl><dt>Voltage</dt><dd id=voltage>--</dd><dt>Estimate</dt><dd id=battery>--</dd><dt>Valid reading</dt><dd id=batteryValid>--</dd><dt>USB</dt><dd id=usb>--</dd><dt>Charger input</dt><dd id=charging>--</dd></dl></section>"
    "<section class=card><h2>IMU</h2><dl><dt>Status</dt><dd id=imu>--</dd><dt>WHO_AM_I</dt><dd id=who>--</dd><dt>Interrupt</dt><dd id=interrupt>--</dd><dt>Accelerometer X / Y / Z</dt><dd id=accel>--</dd><dt>Gyroscope X / Y / Z</dt><dd id=gyro>--</dd><dt>Revolutions</dt><dd id=revs>--</dd><dt>Cadence</dt><dd id=cadence>--</dd></dl></section>"
    "<section class=card><h2>HX711</h2><dl><dt>Status</dt><dd id=hx>--</dd><dt>Raw counts</dt><dd id=raw>--</dd><dt>Filtered counts</dt><dd id=filtered>--</dd><dt>Read failures</dt><dd id=failures>--</dd><dt>Calibration</dt><dd id=cal>--</dd><dt>Torque</dt><dd id=torque>--</dd></dl></section>"
    "<section class=card><h2>Runtime & Network</h2><dl><dt>Uptime</dt><dd id=runtime>--</dd><dt>Firmware</dt><dd>" OPENWATTS_FIRMWARE_VERSION "</dd><dt>Bluetooth</dt><dd id=ble>--</dd><dt>Wi-Fi mode</dt><dd id=wifi>--</dd><dt>Power source</dt><dd id=source>--</dd></dl></section></div><div class=result id=updated>Waiting for diagnostics…</div>"
    "<script>" CORE_JS "async function refresh(){try{const s=await getStatus();put('voltage',s.battery_valid?fmt(s.battery_voltage,3)+' V':'Unavailable');put('battery',s.battery_valid?s.battery_percent+'%':'--');put('batteryValid',s.battery_valid?'Yes':'No');put('usb',s.usb?'Connected':'Disconnected');put('charging',s.charging?'Active':'Inactive');put('imu',s.imu?'Ready':'Unavailable');put('who','0x'+Number(s.imu_whoami||0).toString(16).padStart(2,'0'));put('interrupt',s.imu_interrupt?'High':'Low');put('accel',(s.accel||[]).map(v=>fmt(v,3)+' g').join(' / '));put('gyro',(s.gyro||[]).map(v=>fmt(v,2)+' dps').join(' / '));put('revs',s.revolutions);put('cadence',fmt(s.cadence,2)+' RPM');put('hx',s.hx?'Detected':'Unavailable');put('raw',s.raw);put('filtered',fmt(s.filtered,2));put('failures',s.failures);put('cal',s.calibrated?'Valid':'Not calibrated');put('torque',s.calibrated?fmt(s.torque,3)+' Nm':'Unavailable');put('runtime',uptime(s.uptime).replace('Uptime: ',''));put('ble',s.ble?'Connected':'Advertising');put('wifi',s.wifi_battery?'Battery override':'USB maintenance');put('source',s.usb?'USB':'Battery');$('updated').className='result ok';put('updated','Updated · '+new Date().toLocaleTimeString())}catch(e){$('updated').className='result bad';put('updated',e.message)}setTimeout(refresh,1000)}refresh()</script>" PAGE_FOOT;

#undef CORE_JS
#undef PAGE_FOOT
#undef PAGE_HEAD

}  // namespace openwatts::webui
