[env:esp32c3]
platform = espressif32 @ 6.11.0
platform_packages =
    platformio/framework-espidf @ ~3.50401.0
    platformio/toolchain-riscv32-esp @ 14.2.0+20241119
board = esp32-c3-devkitm-1
framework = espidf
monitor_speed = 115200
board_build.partitions = partitions.csv
board_upload.flash_size = 4MB

build_flags =
    -std=gnu++17
    -DOPENWATTS_FIRMWARE_VERSION=\"1.0.10\"

build_unflags =
    -std=gnu++11

[env:esp32c3_diagnostic]
extends = env:esp32c3
build_flags =
    ${env:esp32c3.build_flags}
    -DOPENWATTS_DIAGNOSTIC_BUILD=1
